### ISSUE TITLE
VIES Status code

### ISSUE THREAD

**Issue by AllanIversen** [jofme/D365FinanceToolbox#73]
We have issues with the "Vies Status code".

We tried to run using a range of VAT#.

We got 173 "Invalid" responses:

57 responses: True negatives.
8 responses:  False negatives - response member state unavailable ("MS_UNAVAILABLE")
108 responses: False negatives - response member state limit exceeded ("MS_MAX_CONCURRENT_REQ")

The response logged for the false negatives:
```
{
  "actionSucceed" : false,
  "errorWrappers" : [ {
    "error" : "MS_UNAVAILABLE"
  } ]
}

```
```
{
  "actionSucceed" : false,
  "errorWrappers" : [ {
    "error" : "MS_MAX_CONCURRENT_REQ"
  } ]
}
```

The enum FTBXECVIESVATNumberStatus has the outcomes: "NotChecked", "Valid", "Invalid", "VIESError" and "VIESNotAvailable".

As-is: For false negatives "Invalid" is assigned.
To-be: For false negatives "VIESError" is assigned.

I guess the problem is within:
https://github.com/jofme/D365FinanceToolbox/blob/db2b5465ace1a421bd14a5057a1066245943a488/Metadata/FinanceToolbox/FinanceToolbox/AxClass/FTBXECVIESInterfaceSingle.xml#L119

Also isMemberStateAvailable might not work 100%, but that's how it is.
https://github.com/jofme/D365FinanceToolbox/blob/db2b5465ace1a421bd14a5057a1066245943a488/Metadata/FinanceToolbox/FinanceToolbox/AxClass/FTBXECVIESInterfaceSingle.xml#L196

Finally it could be great to have an additional enum outcome: "Cancelled" that could be manually assigned. 
If an invalid VAT# has been created, then used, expires and is now end-of-life, then "Cancelled" could be used to exclude the VAT# for any further validations.  Primarily to exclude it from any future user follow-up that otherwise would be required.

**Comment by jofme** [comment]
Thanks, I'll have a look at it.
I think some of the issues comes from missing rate limiting.

**Comment by AllanIversen** [comment]
Sounds great! 
The rate limiting is not implemented for the caller, but at the member state level. 
Based on my observations, the only option under our control, is to schedule the call on Sundays.
Details: https://ec.europa.eu/taxation_customs/vies/#/self-monitoring

**Comment by jofme** [comment]
Hi Allan,
I have implemented the changes now, sorry for the delay!

Instead of adding the "Cancelled" outcome, I've added a new field to the VAT numbers called Lifecycle status. The thought behind it is that I avoid having to make changes to the forms, and that it's possible in the future to add additional lifecycle statuses.

I have also introduced a new delay parameter on the VIES parameters, but it's defaulting to a set value. If it encounters a concurrency error, it increases the delay in intervals of 300MS until it reaches a total of 2 seconds per call.

If you want to have a play I have a tier-2 machine you can test in, otherwise I plan to make a PR later today after I have validated that everything works as expected.

**Comment by AllanIversen** [comment]
Hi Jonas,
Sounds perfect.
Happy to do testing on your t2 env.
Sending you a PM.

Regarding delay:
The rate limitations are not based on the individual caller activity and based on this, the delay implemented might not be that helpful?
Would prefer that false negatives are queued to the next run (24h on when ever the next run is scheduled). 

Lifecycle status:
Good idea. Looking forward to try it. ☺️

**Comment by jofme** [comment]
Thanks!

The delay will be for all subsequent calls. 

I haven't made if per member state, as my assumption is that if we are getting throttled but one it will most likely also trigger other member states. Per member state throttling might be easy to implement but need to think a bit about it.
As it is now, the job will stop trying and queue the remaining numbers for next run.

**Comment by AllanIversen** [comment]
Discoveries:
D1)
Action: Clicking on "VIES VAT number checks -> Results -> Tax excempt number":
Error: Unable to View details, no form exists for table 'FTBXECVIESVATNumUsed'
D2)
"VIES status" field: Enum outcome @FinanceToolbox:VIESCancelled is still present 
D3) 
Any errors seems to stop further processing. DEMF-000000003 should have 100 codes checked, but aborted after 59 (Properly due to "Request limited reached" message from DNK)
Also any errors are not accounted for in the totals. Please refer to screenshot below.
D4)
Checking a single row from the "Tax Registration" form: It's confusing that NO infolog is shown, if the member state is not enabled or unavailable.

Not checked:
N1) Re-run after period of time (30 days). I will check at a later date.

General comments:
C1) Lifecycle handling works perfectly .. Thank you!
C2) I am still not sure the throttling is beneficial. If I leave the parameter to 1ms, will it then be close to disabled?

In general the feature is very close to complete! I still have a few nice to have comments, but hey you have a great feature by now. ;)

<img width="825" height="640" alt="Image" src="https://github.com/user-attachments/assets/6a51984a-9eb1-46c4-9be3-65705ca61111" />

**Comment by jofme** [comment]
Thanks a bunch! I'll get it sorted now
I know why the count is not working, and it should be an easy fix. 

And I do agree, we could use more Infolog messages (-:

**Comment by jofme** [comment]
The issues should be sorted now, minus the view details on the VAT number. Need to think about how to solve it best as the VAT number can originate from multiple places.

I have changed it so that it runs without delays by default, meaning you have to enable throttling if for some reason you need to. I haven't received any request limit errors, so I wonder if we had a bunch of others doing validation at the same time.

**Comment by jofme** [comment]
I removed the jumpref's on the VAT numbers for now, since it might require some more work. I'll add a new issue for this
